glue-viz/glue-jupyter

.travis.yml, environment.yml, setup.py
Also switch to codecov for coverage since it produces nicer results
=> WIP: Use ci-helpers to simplify the conda set-up

notebooks/Distance to The Pleiades with Glupyter and Gaia DR2.ipynb
This is a notebook that contains a mildly cleaned-up version of the notebook I built for gluecon 2018.  It doesn't really have enough explanation yet, nor does it have the "compare to isochrone" I want to include as a "killer app" example.  But I'm putting it here so that it doesn't get lost in case I don't finish.
@maartenbreddels @astrofrog - if you'd like we could just merge this and I can do the things I mention above later in a follow-on PR.  Or if you'd rather keep the examples cleaner it can wait until I update this PR.
=> First cut at Gaia Pleaides notebook

glue_jupyter/bqplot/tests/test_bqplot.py, glue_jupyter/bqplot/view.py
=> Add support for equal aspect for the bqplot image viewer, solves #9

glue_jupyter/bqplot/scatter.py, glue_jupyter/bqplot/tests/test_bqplot.py, glue_jupyter/tests/main_test.py, glue_jupyter/utils.py
depends on an upcoming fix in the scatter_webgl branch of bqplot
=> Implement cmap_mode=Linear for bqplot scatter plot

environment.yml, glue_jupyter/__init__.py, glue_jupyter/bqplot/view.py, glue_jupyter/conftest.py, glue_jupyter/link.py, glue_jupyter/tests/main_test.py, glue_jupyter/utils.py
cc @eteq 
This is the start to address https://github.com/glue-viz/glue-jupyter/issues/36 and to become a more user friendly API.
The most common arguments should be included as method arguments, other state values can be passed through the viewer_state dict or layer_state dict.
=> Initial values for plotting method

glue_jupyter/bqplot/histogram.py, glue_jupyter/bqplot/scatter.py, glue_jupyter/bqplot/tests/test_bqplot.py, glue_jupyter/bqplot/view.py, glue_jupyter/utils.py
With this PR we should be able to use vaex, using this package: https://github.com/glue-viz/glue-vaex
=> WIP: Vaex/BaseData support for bqplot histogram and scatter2d

glue_jupyter/bqplot/histogram.py, glue_jupyter/bqplot/scatter.py, glue_jupyter/bqplot/tests/data/bqplot.ipynb, glue_jupyter/bqplot/tests/test_bqplot.py, glue_jupyter/conftest.py, glue_jupyter/ipyvolume/scatter.py, glue_jupyter/ipyvolume/tests/data/ipyvolume.ipynb, glue_jupyter/ipyvolume/tests/test_ipyvolume.py, glue_jupyter/ipyvolume/volume.py, glue_jupyter/matplotlib/tests/data/matplotlib.ipynb, glue_jupyter/matplotlib/tests/test_matplotlib.py
This is a work in progress - for now this adds regression tests that highlight the issues with the bqplot and ipyvolume viewers.
=> Fix issues with incompatible subsets

setup.cfg
I forgot to do this when changing to setup.cfg
=> Install ipywidgets and ipyvolume from git

glue_jupyter/bqplot/tests/test_bqplot.py, glue_jupyter/bqplot/view.py
Fixes https://github.com/glue-viz/glue-jupyter/issues/65
=> Fix bug that caused rectangular selection to not work properly

glue_jupyter/bqplot/image/frb_mark.py
At the moment the image viewer only updates if the user stops moving a slider in the layer options, but we ideally want this to be updated ASAP. This PR makes it so that we only used the debounced version of the method when panning/zoomming. Ideally we'd solve #82 but for now I think this is better than what we have in master (which I added in #75)
=> Only use debounced when panning/zooming

glue_jupyter/bqplot/image/frb_mark.py, glue_jupyter/bqplot/image/layer_style_widget.py
Fixes https://github.com/glue-viz/glue-jupyter/issues/81
=> Added dropdown for attribute and stretch in image viewer

README.md
I find this patch make things clearer, at least for myself.
=> DOC: Clarify installation

binder/setup.sh, docs/installing.rst, setup.cfg
=> Updated installation instructions for Jupyter Lab

docs/api.rst, docs/developer_notes.rst, docs/getting_started.rst, docs/index.rst, glue_jupyter/common/state3d.py, glue_jupyter/ipyvolume/scatter/layer_artist.py, glue_jupyter/ipyvolume/scatter/viewer.py, glue_jupyter/ipyvolume/volume/layer_artist.py, glue_jupyter/ipyvolume/volume/viewer.py, glue_jupyter/tests/data/state_widgets.ipynb
The docs are now being built on Travis and pushed to gh-pages (RTD can't deal with installing widget packages from source with webpack, due to memory issues). So I'm now going to start expanding the docs as part of a STScI development sprint.
The goal here is to document things as they are, not as they should be - nothing is set in stone, so we can still change some aspects of the API if needed!
=> Write more documentation

glue_jupyter/bqplot/common/tools.py, glue_jupyter/bqplot/scatter/layer_artist.py, glue_jupyter/common/state_widgets/layer_scatter.py
Just a couple of small bug fixes
=> Fix scatter visibility and vertical selection bug

binder/setup.sh, docs/installing.rst, glue_jupyter/bqplot/image/frb_mark.py, glue_jupyter/bqplot/scatter/layer_artist.py, setup.cfg
I've now released a stable version of bqplot-image-gl
=> Switch to bqplot-image-gl and update bqplot to master version

glue_jupyter/bqplot/common/viewer.py, glue_jupyter/bqplot/histogram/layer_artist.py, glue_jupyter/bqplot/histogram/tests/test_viewer.py, glue_jupyter/bqplot/image/tests/test_viewer.py, glue_jupyter/bqplot/profile/layer_artist.py, glue_jupyter/bqplot/profile/tests/test_viewer.py, glue_jupyter/bqplot/scatter/layer_artist.py, glue_jupyter/bqplot/scatter/tests/test_viewer.py, glue_jupyter/bqplot/tests/test_bqplot.py, glue_jupyter/common/state3d.py, glue_jupyter/common/state_widgets/layer_histogram.py, glue_jupyter/common/state_widgets/layer_image.py, glue_jupyter/common/state_widgets/layer_profile.py, glue_jupyter/conftest.py, glue_jupyter/data.py, glue_jupyter/ipyvolume/scatter/layer_artist.py, glue_jupyter/ipyvolume/scatter/tests/__init__.py, glue_jupyter/ipyvolume/scatter/tests/test_viewer.py, glue_jupyter/ipyvolume/volume/layer_artist.py, glue_jupyter/ipyvolume/volume/layer_style_widget.py, glue_jupyter/ipyvolume/volume/tests/test_viewer.py, glue_jupyter/link.py, glue_jupyter/tests/main_test.py, glue_jupyter/utils.py, glue_jupyter/widgets/color.py, glue_jupyter/widgets/size.py, setup.cfg
Fixes #105
Fixes #104 
Fixes #103
=> Fix several usability bugs

binder/setup.sh, docs/installing.rst, setup.cfg
This simplifies the installation instructions and binder set-up a little.
=> Use latest alpha release of bqplot

setup.cfg
As well as the latest alpha release of bqplot
=> Use latest stable releases of glue and glue-vispy-viewers

.travis.yml, glue_jupyter/common/toolbar.py, glue_jupyter/widgets/linked_dropdown.py, glue_jupyter/widgets/subset_mode.py, glue_jupyter/widgets/subset_mode_test.py, glue_jupyter/widgets/subset_select.py, glue_jupyter/widgets/subset_select_test.py, glue_jupyter/widgets/tests/test_linked_dropdown.py, setup.cfg
https://github.com/glue-viz/glue-jupyter/pull/124 wasn't sufficient to fix compatibility with ipymateiralui 0.1.1 - this PR gets everything working again.
=> Fixes for ipymaterialui 0.1.1

glue_jupyter/bqplot/scatter/layer_artist.py, glue_jupyter/bqplot/tests/test_bqplot.py
a few fixes to make the density_map work.
=> fix: convert counts to float32 and flip x and y components

MANIFEST.in, azure-pipelines.yml, pyproject.toml, setup.py, tox.ini
With this, releases will automatically be built and uploaded to PyPI whenever a ``v???`` tag is pushed to the repository.
=> Added configuration for auto-releasing with Azure

glue_jupyter/utils.py, glue_jupyter/vuetify_layout.py, glue_jupyter/widgets/subset_mode_vuetify.py, glue_jupyter/widgets/subset_select_vuetify.py
=> Generalize subset-related global widgets to work with session objects not just viewers

CHANGES.rst, glue_jupyter/bqplot/common/viewer.py, glue_jupyter/bqplot/histogram/layer_artist.py, glue_jupyter/bqplot/histogram/tests/test_viewer.py, glue_jupyter/bqplot/image/frb_mark.py, glue_jupyter/bqplot/image/layer_artist.py, glue_jupyter/bqplot/image/tests/test_viewer.py, glue_jupyter/bqplot/profile/layer_artist.py, glue_jupyter/bqplot/profile/tests/test_viewer.py, glue_jupyter/bqplot/scatter/layer_artist.py, glue_jupyter/bqplot/scatter/tests/test_viewer.py, glue_jupyter/widgets/linked_dropdown.py
@nmearl - this should fix the removal of data from bqplot viewers
=> Fix removal of data from bqplot viewers

CHANGES.rst, azure-pipelines.yml, glue_jupyter/bqplot/common/tools.py, glue_jupyter/bqplot/image/viewer.py, glue_jupyter/bqplot/scatter/viewer.py, glue_jupyter/bqplot/tests/test_bqplot.py, setup.cfg, tox.ini
This implements circular brushing using https://github.com/bloomberg/bqplot/pull/1050 and https://github.com/glue-viz/glue/pull/2094 
TODO
=> feat: circular brushing

CHANGES.rst, glue_jupyter/__init__.py, glue_jupyter/bqplot/common/tools.py, glue_jupyter/common/state_widgets/viewer_image.py, glue_jupyter/tests/main_test.py, glue_jupyter/utils.py
These are just a few fixes related to functionality being developed in jdaviz
=> Miscellaneous fixes

glue_jupyter/__init__.py, glue_jupyter/app.py
@nmearl - this should ensure that glue plugins are loaded in jdaviz, including those required for the auto-linking.
=> Load plugins when calling JupyterApplication

glue_jupyter/state_traitlets_helpers.py, glue_jupyter/tests/test_state_traitlets_helpers.py
Updates the state/dictionary serialization functions to properly handle `CallbackDict` objects.
=> Handle CallbackDict state type in serializers

glue_jupyter/common/state_widgets/viewer_image.py, glue_jupyter/common/state_widgets/viewer_image.vue
Displays the world value of the current slice along with the slice index for a cube image displayed in the image viewer widget
=> Display world value on image viewer slider

glue_jupyter/state_traitlets_helpers.py, glue_jupyter/tests/test_state_traitlets_helpers.py
@nmearl - this should fix the issue you were seeing with UUIDs making their way back to the glue state.
=> Fix syncing of state from JSON when nested MAGIC_IGNORE values were present

CHANGES.rst, glue_jupyter/bqplot/common/tools.py, glue_jupyter/bqplot/image/tests/test_viewer.py, glue_jupyter/bqplot/profile/layer_artist.py, glue_jupyter/state_traitlets_helpers.py, glue_jupyter/tests/test_state_traitlets_helpers.py, glue_jupyter/utils.py
This fixes a couple of bugs:
* Prevents an error that happened when changing the reference data in the image viewer from a 3-d to a 2-d dataset.
* Ensures that the profile viewer works properly when changing the reference data
=> Fixes to image and profile viewers

binder/Dockerfile
Resolves #186 where binder failed to build. Ended up having to use curl to install nodejs in the Dockerfile @astrofrog.
=> Binder fix

glue_jupyter/app.py, glue_jupyter/common/state_widgets/layer_image.vue, glue_jupyter/common/state_widgets/layer_profile.vue, glue_jupyter/widgets/glue_float_field.vue
=> fix: errors when numeric field is empty or invalid e.g. '1.'

glue_jupyter/table/table.vue, glue_jupyter/table/viewer.py
Enhances the table viewer to allow for row selection and approach callbacks.
=> Allow table viewer row select highlighting

glue_jupyter/bqplot/image/layer_artist.py, glue_jupyter/bqplot/image/state.py, glue_jupyter/bqplot/image/tests/test_viewer.py, glue_jupyter/common/state_widgets/layer_image.py, glue_jupyter/common/state_widgets/layer_image.vue, glue_jupyter/widgets/layer_options.py, setup.cfg, tox.ini
This allows users to then show either the bitmap, contour or both in the image viewer layers.
=> feat: add contour support to image viewer

glue_jupyter/app.py, glue_jupyter/common/state_widgets/layer_image.vue, glue_jupyter/common/state_widgets/viewer_image.vue, glue_jupyter/widgets/glue_throttled_slider.vue
Using lodash the updates are limited to 1 each 300ms
=> fix: image viewer lags behind trying to render each slider position

glue_jupyter/common/state_widgets/layer_image.py
I suspect this is the source of the bug seen in spacetelescope/jdaviz#548
=> MNT: Remove print colormap

CHANGES.rst, glue_jupyter/bqplot/common/viewer.py, glue_jupyter/common/toolbar_vuetify.py
A few small fixes/improvements
=> Make it so that icon can be specified by path

CHANGES.rst, glue_jupyter/widgets/subset_select.vue
This is for ease of CSS customization in jdaviz
=> Add class name to subset_select.vue

glue_jupyter/common/state_widgets/viewer_profile.vue
Simple fix for something that had been bothering users.
=> Fix mislabeled field in profile viewer options

CHANGES.rst, glue_jupyter/common/toolbar_vuetify.py
This switches to using SVG icons for the viewer toolbar.
=> Use SVG icons

glue_jupyter/common/state_widgets/layer_image.py, glue_jupyter/common/state_widgets/tests/test_viewer_image.py
Fixes https://github.com/spacetelescope/jdaviz/issues/574
=> fix: do not overwrite the contour level text input when parsing

glue_jupyter/bqplot/common/tools.py
This PR attempts to add an EllipticalROI selection tool, which can then be used in jdaviz. It currently uses the `glue_lasso` icon because there is not a `glue_ellipse` icon in glue. 
An alternative to this would be to remove the `pixel_aspect` kwarg in the `BqplotCircleMode` in order to allow ellipses in that mode.
resolves #223
=> Add ellipse mode

glue_jupyter/__init__.py, glue_jupyter/app.py, glue_jupyter/bqplot/common/tools.py, setup.cfg, tox.ini
Fix #236 . This is needed for spacetelescope/jdaviz#633 (Imviz MVP).
Bonus: Make test log readable for a human, and test expectations more consistent between tox and non-tox runs.
=> FEAT: Deactivate all other tools in other viewers when region selection tool is active in current viewer

glue_jupyter/bqplot/common/tools.py
User at Imviz Hack Hour confused how to zoom. This clarifies how-to in tooltip. This goes with spacetelescope/jdaviz#749
cc @camipacifici
=> Clarify tooltip for panzoom tool

docs/api.rst
Fixes https://github.com/glue-viz/glue-jupyter/issues/258
=> Added table viewer to API docs

LICENSE
=> Update license year 

glue_jupyter/bqplot/common/viewer.py, glue_jupyter/bqplot/histogram/layer_artist.py, glue_jupyter/bqplot/scatter/layer_artist.py
Fixes #263
Requires:
* https://github.com/jupyter-widgets/pythreejs/pull/368
* https://github.com/bqplot/bqplot/pull/1406
* https://github.com/glue-viz/glue/pull/2236
* https://github.com/maartenbreddels/ipyvolume/pull/390
=> check for deprecation warnings with pytest

glue_jupyter/tests/main_test.py, glue_jupyter/utils.py, glue_jupyter/widgets/subset_mode_vuetify.py, setup.cfg
Hopefully this will fix the CI
=> Fix tests and remove unneeded version checks

binder/Dockerfile, binder/setup.sh
Previously things were broken as glue-core no longer supports Python 3.6
=> Updated binder config to use Python 3.8

CHANGES.rst, glue_jupyter/widgets/layer_options.py, glue_jupyter/widgets/subset_select_vuetify.py
As fixed during the Indigo hack day!
Fixes https://github.com/glue-viz/glue-jupyter/issues/278
=> Fix updating of data and subset label and color in dropdowns

glue_jupyter/common/state_widgets/layer_image.py, glue_jupyter/common/state_widgets/layer_profile.py, glue_jupyter/common/state_widgets/viewer_histogram.py, glue_jupyter/common/state_widgets/viewer_image.py, glue_jupyter/common/state_widgets/viewer_profile.py, glue_jupyter/common/toolbar_vuetify.py, glue_jupyter/table/viewer.py, glue_jupyter/vuetify_helpers.py, glue_jupyter/vuetify_layout.py, glue_jupyter/widgets/layer_options.py, glue_jupyter/widgets/subset_select_vuetify.py
This PR uses the new template loading feature of ipyvue, reducing the amount of code to load a template and enabling hot reloading of templates (https://ipyvuetify.readthedocs.io/en/latest/template_usage.html#hot-reloading)
=> Refactor: use new template loading feature of 

CHANGES.rst
#289 change log is missing the PR number. Tsk tsk, @astrofrog . 😉
=> Fix PR 289 change log

glue_jupyter/table/table.vue, glue_jupyter/table/viewer.py
This PR adds the option to make the table scrollable. Based on the work of @kecnry in spacetelescope/jdaviz#1068
https://user-images.githubusercontent.com/46192475/155126172-fed8d1c9-597f-4f7f-9a3f-b9ec26f61697.mp4
=> feat: add option to make table scrollable

docs/developer_notes.rst
Fixes https://github.com/glue-viz/glue-jupyter/issues/282
=> Add note to developer docs about logger

glue_jupyter/common/state_widgets/viewer_image.vue, glue_jupyter/widgets/layeroptions.vue
Prevent long content from pushing out of view. See https://github.com/spacetelescope/jdaviz/issues/1157.
=> fix: prevent long content from pushing out of view

.github/release.yml, CHANGES.md
Second take at #322; this time in [GH Releasing](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration) syntax!
=> Changelog skips and full diff links

glue_jupyter/state_traitlets_helpers.py, glue_jupyter/utils.py
Just a simple fix, but we were previously checking for Data rather than BaseCartesianData
=> Fix support for all BaseCartesianData subclass instances

CHANGES.md, README.rst, RELEASE_INSTRUCTIONS.md
Updating CHANGES.md and linking release instructions to glue-core.
=> Autorelease updates

.github/workflows/ci_workflows.yml, MANIFEST.in, setup.cfg, tox.ini
=> Updated dependencies to run and test with Python 3.11

setup.cfg
This will hopefully fix the CI
=> Ignore Jupyter warning beyond our control

glue_jupyter/utils.py
Fix https://github.com/glue-viz/glue-jupyter/issues/342
=> MNT: Replace zmq ioloop with tornado

glue_jupyter/bqplot/image/viewer.py
Similar to https://github.com/glue-viz/glue/pull/2344
=> Fix issues that came up while testing on-the-fly reprojection

glue_jupyter/bqplot/common/viewer.py
This will avoid unnecessary updates and fix the jdaviz CI
=> Don't set scale limits if glue state limits are None

glue_jupyter/bqplot/scatter/layer_artist.py, glue_jupyter/bqplot/scatter/tests/test_viewer.py
Should fix https://github.com/glue-viz/glue-jupyter/issues/358
=> Fixed a couple of bugs in the scatter viewer related to incompatible datasets and dataset removal

pyproject.toml
Hopefully giles will be able to start reporting
=> Add giles config to pyproject.toml

tox.ini
Should fix the errors we are seeing on CircleCI
=> Pin pydantic to 1.x for now for compatibility with solara

docs/conf.py, glue_jupyter/conftest.py
Just need to explicitly set ``navigation_with_keys`` to ``False``
=> Fix docs failure related to theme warning

glue_jupyter/conftest.py, tox.ini
I think this should get things running again
=> Fix visual tests with solara

glue_jupyter/__init__.py, setup.cfg
We have to pin solara due to issue in https://github.com/widgetti/solara/issues/606
=> Pin solara to <1.29 for now due to issue with patched rcParams

glue_jupyter/tests/images/py311-test-visual.json
No differences in actual images
=> Updated image hashes

setup.cfg
Added ``ipython_genutils`` to dependencies and see if there are any other issues.
=> Fix continuous integration
