- .travis.yml
- binder/environment.yml
- binder/postBuild
I've restructured the branches in bqplot, and we can now rely on ipyvolume ^0.5.0-beta.1. I guess we need to do the same for https://github.com/glue-viz/glue-example-data/tree/jupyter. Or we make add a postBuild in that repo, that pulls this repo, and executes this postBuild.
> Using ipyvolume 0.5, enabled Jupyter Lab, and merge two rebased branches of bqplot

- glue_jupyter/__init__.py
I've used the <dataset>:<subset> format, instead of putting dataset behind the subset, which to me feel more natural.
> Include dataset label in tab labels, resolves #11

- glue_jupyter/bqplot/tests/test_bqplot.py
- glue_jupyter/bqplot/view.py
A feature request in glue (https://github.com/glue-viz/glue/issues/1591) and was already enabled for the ipyvolume viewer, and now enabled for the bqplot viewers as well.
It would be nice to put in the `show_axes` somewhere in the state.
This seems to exposes a bug for the webgl accelerated parts in bqplot (image viewer and scattermega), it seems to work fine for the histogram. So we could merge this, or keep open until that is fixed.
> Implement show axes for bqplot

- .travis.yml
- binder/postBuild
- environment.yml
- glue_jupyter/bqplot/image.py
- glue_jupyter/bqplot/scatter.py
Use https://github.com/glue-viz/ipyastroimage for the bqplot Image mark, instead of trying to get all we want in bqplot.
Since we want astronomy related parts in the image mark, and want to move fast, it makes more sense to continue development outside of bqplot.
> Move to using ipyastroimage

- glue_jupyter/bqplot/view.py
- glue_jupyter/ipyvolume/scatter.py
- glue_jupyter/ipyvolume/tests/test_ipyvolume.py
- glue_jupyter/ipyvolume/view.py
- glue_jupyter/widgets/__init__.py
- glue_jupyter/widgets/color.py
- glue_jupyter/widgets/component.py
- glue_jupyter/widgets/component_test.py
Similar to #43 a widget takes the responsibility for managing ui state and glue state, makes testing and reusing much easier.
Also using ipymaterialui for a more consistent look
TODO: remove all use of link_component_id_to_select_widget
> WIP: Widget component

- glue_jupyter/bqplot/scatter/layer_artist.py
This reduces the default size of markers in the 2D scatter viewer.
Note that this needs to be rebased once https://github.com/glue-viz/glue-jupyter/issues/68 is merged!
Fixes https://github.com/glue-viz/glue-jupyter/issues/13
Fixes https://github.com/glue-viz/glue-jupyter/issues/66
> Fix default size of points in scatter viewer

- glue_jupyter/bqplot/image/layer_artist.py
- glue_jupyter/bqplot/tests/test_bqplot.py
This should be rebased once #68 is merged.
Fixes https://github.com/glue-viz/glue-jupyter/issues/54
> Fix issue with image viewer when data is not floating-point

- glue_jupyter/bqplot/common/viewer.py
Just a minor UI change, I think it would make more sense for the selection tools to be next to the rest of the selection toolbar:
> Move selection buttons in bqplot into toolbar above viewer

- glue_jupyter/bqplot/common/__init__.py
- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/bqplot/histogram/viewer.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/profile/viewer.py
- glue_jupyter/bqplot/scatter/viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
- glue_jupyter/common/toolbar.py
- glue_jupyter/ipyvolume/common/__init__.py
- glue_jupyter/ipyvolume/common/tools.py
- glue_jupyter/ipyvolume/common/viewer.py
- glue_jupyter/matplotlib/base.py
- glue_jupyter/matplotlib/histogram.py
- glue_jupyter/matplotlib/image.py
- glue_jupyter/matplotlib/scatter.py
- glue_jupyter/view.py
This refactors all code related to selection tools to use the glue CheckableTool infrastructure, and define a general toolbar class. This also enables the use of all the default Matplotlib tools (thanks to https://github.com/glue-viz/glue/pull/1983 and https://github.com/glue-viz/glue/pull/1984).
> Refactor tools to use glue infrastructure

- docs/developer_notes.rst
- glue_jupyter/__init__.py
- glue_jupyter/app.py
- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
- glue_jupyter/common/state_widgets/viewer_histogram.py
- glue_jupyter/common/state_widgets/viewer_image.py
- glue_jupyter/common/state_widgets/viewer_profile.py
- glue_jupyter/common/state_widgets/viewer_scatter.py
- glue_jupyter/ipyvolume/common/tools.py
- glue_jupyter/ipyvolume/common/viewer.py
- glue_jupyter/ipyvolume/common/viewer_options_widget.py
- glue_jupyter/ipyvolume/scatter/viewer.py
- glue_jupyter/ipyvolume/tests/test_ipyvolume.py
- glue_jupyter/ipyvolume/volume/viewer.py
- glue_jupyter/matplotlib/base.py
- glue_jupyter/view.py
- glue_jupyter/widgets/layer_options.py
This tidies up a lot of the code that does the layout for the viewers to be defined in the base class for all Jupyter-based viewers. In addition, this defines a public API for accessing the components for any given viewer, and provides a way to register a custom 'layout factory' that defines a new default layout for viewers, for example:
```python
from ipywidgets import VBox
from glue_jupyter import set_layout_factory
def simple_viewer_layout(viewer):
return VBox([viewer.toolbar_selection_tools, viewer.figure_widget])
set_layout_factory(simple_viewer_layout)
```
This will make it easier to experiment with ipyvuetify layouts.
Finally, this creates a new widget for editing layer options which consists of a way to select the current layer (for now a dropdown) and shows the options for that …
> Tidy up how layout is defined for viewers and provide a way to customize

- glue_jupyter/matplotlib/base.py
As of 0.3.0, FigureCanvasNbAgg and FigureManagerNbAgg have been renamed.
In this patch we try the new names but fall back to the old ones if needed.
> glue_jupyter/matplotlib/base.py: track changes in latest ipympl

- glue_jupyter/widgets/linked_dropdown.py
- glue_jupyter/widgets/subset_mode.py
- glue_jupyter/widgets/subset_select.py
The `Div` bindings seems to have been removed in the latest versions of ipymaterialui. Replacing with the `Html` component seems to solve the issue.
> Replace deprecated Div reference with Html

- glue_jupyter/app.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
- glue_jupyter/bqplot/tests/data/bqplot.ipynb
- glue_jupyter/bqplot/tests/test_bqplot.py
- glue_jupyter/ipyvolume/scatter/tests/test_viewer.py
- glue_jupyter/ipyvolume/tests/data/ipyvolume.ipynb
- glue_jupyter/ipyvolume/tests/test_ipyvolume.py
- glue_jupyter/matplotlib/tests/data/matplotlib.ipynb
- glue_jupyter/tests/main_test.py
- glue_jupyter/utils.py
- glue_jupyter/view.py
- notebooks/Astronomy/W5/W5 Tutorial.ipynb
- notebooks/Generic/demo_gaussian.ipynb
- notebooks/Planes/Boston Planes.ipynb
This does two things:
* It allows data to be specified using the data labels both when creating viewers and when calling ``add_data`` later.
* It changes the arguments for the viewers to be keyword-only (see https://github.com/glue-viz/glue-jupyter/issues/73 for a discussion). This might  compatibility with some existing notebooks but I think this is better to fix before we actually have a first stable release.
> Allow data as strings and change to kwarg-only arguments for viewers

- glue_jupyter/__init__.py
- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/common/toolbar_vuetify.py
- glue_jupyter/ipywidgets_layout.py
- glue_jupyter/matplotlib/base.py
- glue_jupyter/view.py
- glue_jupyter/vuetify_layout.py
- glue_jupyter/widgets/layer_options.py
- glue_jupyter/widgets/subset_mode_vuetify.py
- glue_jupyter/widgets/subset_select_vuetify.py
- setup.cfg
This starts to implement a vuetify-based interface for viewers. To try it out:
```python
from glue_jupyter import set_layout_factory
from glue_jupyter.vuetify_layout import vuetify_layout_factory
set_layout_factory(vuetify_layout_factory)
```
Preview of scatter viewer with sidebar collapsed:
and with sidebar open:
I haven't yet re-implemented the way to allow multiple subset selections, but it's definitely possible. Also, the viewer and layer options in the sidebar still use ipywidgets - for now we might want to keep this as is since it's actually pretty compact.
> Started re-implementing layout with vuetify

- glue_jupyter/app.py
- glue_jupyter/table/__init__.py
- glue_jupyter/table/table.vue
- glue_jupyter/table/tests/test_table.py
- glue_jupyter/table/viewer.py
Although ipysheet was discussed as a table viewer, I don't think it is the proper widget to do this. It does not enforce a common datatype per column, since it models a spreadsheet, not columnar data. Also, it will be limited in the amount of data it can handle (e.g. don't expect to view the Gaia dataset with it).
Experimenting with vuetify's data table, I've been able to put together a table viewer that will do kernel side pagination, is consistent with the ipyvuetify look, and more easy to customize to our needs.
Note that when we move to vuetify 2.0+, [the data table also has a dense layout](https://vuetifyjs.com/en/components/data-tables#dense)
Example usage (rebased on the vuetify layout branch #115)
Example using ~1 billion rows (Gaia data):
> feat: add table viewer based in ipyvuetify

- azure-pipelines.yml
- binder/setup.sh
- docs/installing.rst
- glue_jupyter/bqplot/scatter/layer_artist.py
- setup.cfg
- tox.ini
This fixes the Azure configuration to use ``macos`` instead of ``macosx``
I've also switched to using the stable version of bqplot! :tada:
Fixes #114
> Fix Azure Pipelines configuration for Mac builds

- glue_jupyter/__init__.py
- glue_jupyter/common/slice_helpers.py
This fixes the test suite for the changes in https://github.com/glue-viz/glue/pull/2079 - but in fact the changes here are more general, and are to make sure things work correctly if ``Data.coords`` is ``None``
> Fix case where Data.coords is None

- glue_jupyter/ipyvolume/common/viewer.py
- glue_jupyter/ipyvolume/scatter/layer_artist.py
- glue_jupyter/ipyvolume/tests/test_ipyvolume.py
> fix: flip y and z axis of ipyvolume scatter to be consistent with glue-qt (z-up)

- glue_jupyter/ipyvolume/common/viewer.py
- glue_jupyter/ipyvolume/scatter/tests/test_viewer.py
Now we link the attribute labels to the labels of ipyvolume. The link is directional, so only when the attribute changes does the plot label change, not the other way around.
I am sure when the label gets changed how i should detect that.
This PR assumes #150 is merged, since it flips y and z.
> feat: dlink attribute labels to ipvolume labels

- glue_jupyter/ipyvolume/scatter/layer_artist.py
- glue_jupyter/ipyvolume/scatter/layer_style_widget.py
Fix for #144. Change the default scatter3d marker to diamond for performance reasons. Also add circle_2d as a marker option for a better performing circular option.
> Scatter 3D Default Marker

- CHANGES.rst
- glue_jupyter/bqplot/profile/layer_artist.py
This PR fixes #160 and is related to https://github.com/glue-viz/glue/pull/2095
> Fix issue where profile of subset was not correctly hidden if the subset was emptied

- CHANGES.rst
- glue_jupyter/widgets/subset_select.vue
- glue_jupyter/widgets/subset_select_vuetify.py
For now enabling this option will require modifying a trait on the widget, which can't easily be done via the notebook, but in future we could choose to expose an 'advanced' mode that would enable this (and other) options.
Fixes #159
> Make the 'allow multiple subsets' toggle optional and disable it by default

- CHANGES.rst
- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/common/toolbar_vuetify.py
This improves the behavior of selection tools - for now the main change is to make the selections 'single use' as in the Qt application which we have found reduces confusion and mistakes.
The next step is to make it so that if the user clicks on a region and drags it it should move.
Once finished this should fix https://github.com/glue-viz/glue-jupyter/issues/158
> Improve behavior of selection tools

- CHANGES.rst
- glue_jupyter/widgets/subset_select.vue
- glue_jupyter/widgets/subset_select_vuetify.py
- setup.cfg
This almost works but the drop-down menu doesn't go away when I click on the remove button:
The subset is removed from the list, it's more that the UI doesn't refresh immediately. Code for the above example:
```python
import numpy as np
import glue_jupyter as gj
app = gj.jglue(data={'x': np.random.normal(0, 1, 100), 'y':np.random.normal(0, 1, 100)})
scatter_viewer = app.scatter2d()
```
Closes https://github.com/glue-viz/glue-jupyter/issues/161
> Implement a way to remove subsets

- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/common/toolbar_vuetify.py
- glue_jupyter/view.py
- setup.cfg
This reverts a change I made in #164 which de-selected a selection tool after a selection was made.
There are still some issues with some events being still passed to the circular selection even once the circular selection is deselected. See the following screencast:
This shows:
* Making rectangular selections works
* Once I deselect the tool selections don't work (=good)
* When I select the circular selection tool selections work
* When I switch back to the rectangular selection there is a small glitch
* When I disable the rectangular selection now clicking causes the circular selection to come back and get updated.
* Another issue is that the circular selection brush color seems to be ignored and is shown in green
@maartenbreddels - could you see if you can reproduce this and …
> Fix behavior of selection tools

- glue_jupyter/widgets/layeroptions.vue
Prevent Javascript errors when plots are empty.
> fix: handle empty plot

- glue_jupyter/common/state_widgets/layer_image.vue
- glue_jupyter/common/state_widgets/viewer_image.vue
The .vuetify-styles selector is only available in the notebook
context and thus will not be applied when used in voila-vuetify.
> fix: don't use css selector specific to notebook context

- glue_jupyter/state_traitlets_helpers.py
Fixes an issue in which the json serialization would fail on numpy dtypes:
`TypeError: Object of type 'int64' is not JSON serializable`
> Handle numpy serialization in json

- glue_jupyter/bqplot/common/viewer.py
Small change to display component world attribute units in bqplot. If no data exists yet, the units are ignored.
> Display proper units information on bqplot axes

- CHANGES.rst
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
Previously, the pixels weren't really showing up as squares, but this now hooks in to the glue-core infrastructure to make it work properly. For some reason, when switching to 'auto' aspect ratio, the image doesn't change, because somehow changes to ``scale_x/y.min/max`` don't seem to be updating the figure. But as-is, this is already an improvement and I think consistent with how glue Qt works.
> Fix setting of equal aspect ratio for image viewer

- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/profile/viewer.py
This PR adds two buttons to the bqplot profile viewer toolbar, one to zoom/pan only the x-axis, the other for the y-axis. Right now both buttons use the existing glue_move icon (the one used for general pan/zoom) as a placeholder, which should be replaced before this is merged. I'll catch up with Jenn soon about making those.
Tagging in some people I know this is of interest to: @nmearl @dtn5ah @javerbukh @robelgeda
> Adding single axis zoom tools to 1D profile viewer toolbar

- setup.cfg
cc @eteq 
This updates the dependencies for glue-jupyter, required for jdaviz:
bqplot-image-gl:
* Fixes https://github.com/spacetelescope/jdaviz/issues/218
bqplot:
* https://github.com/bqplot/bqplot/issues/1174
One could argue these should go into jdaviz, but I think these fix general issues that affect glue-jupyter.
Note: bqplot-image-gl is not released yet, it requires @astrofrog to give me maintainer rights
> chore: update dependencies

- glue_jupyter/bqplot/common/viewer.py
Capture of the behavior before this fix:
This should fix: https://github.com/spacetelescope/jdaviz/issues/245
> fix: prevent feedback loop when panning in image viewer

- glue_jupyter/bqplot/image/layer_artist.py
Jdaviz has reported issue #[295](https://github.com/spacetelescope/jdaviz/issues/295) when trying to change the image displayed in the image viewer after the contours update since eae1c83f9744440e6fdf17a4858c44abad6a2b66. Basically if no contours are selected, we get a crash when the image layer artist tries to remove the contour marks anyways. This one line check (checking if the contours are in the marks before attempting removal) seems to fix things on our end.
Thanks!
Duy
> Check if contours are in image before layer_artist attempts removal

- CHANGES.rst
- glue_jupyter/bqplot/image/state.py
The attribute helper for contours was named the same as the one for the image itself which meant that the image attribute helper for the percentile was not working - this fixes the issue.
> Fix image percentile setting

- glue_jupyter/common/state_widgets/viewer_image.vue
When an empty slices property is received from the backend, but
the sliders property is not yet updated, the slider will add its
default value to the slices list, thereby changing the state
which gets synced back to the backend.
Releted to: spacetelescope/jdaviz#446
> fix: client-side state change triggered by update from backend

- binder/Dockerfile
Bump nodejs to 14.x (current LTS version). Fixes the binder build.
[Broken binder build](https://mybinder.org/v2/gh/glue-viz/glue-jupyter/master?filepath=notebooks%2FAstronomy%2FL1448%2FL1448%20in%203D.ipynb), excerpt from the error message:
```
+ jupyter labextension install @jupyter-widgets/jupyterlab-manager ipyvolume jupyter-threejs bqplot bqplot-image-gl jupyter-vuetify --no-build
An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-bqfn_mon.log
Removing intermediate container 0a32fb970968
```
[Fixed binder build](https://mybinder.org/v2/gh/sk1p/glue-jupyter/fix-nodejs-deps?filepath=notebooks%2FAstronomy%2FL1448%2FL1448%20in%203D.ipyn …
> Update nodejs version for binder container

- CHANGES.rst
- glue_jupyter/app.py
- glue_jupyter/tests/main_test.py
Prior to this PR this defaulted to the base class implementation which was an empty list
> Implement JupyterApplication.viewers

- glue_jupyter/bqplot/common/viewer.py
@maartenbreddels - does this seem reasonable? We could optimize further so that ``remove_event_callback`` does the right thing but I'm not convinced this matters as much - what do you think? (I mean we could add it, but seems lower priority - at least with this current PR regular glue-jupyter users who don't need callbacks won't see a performance penalty).
> Don't always listen to all events by default

- glue_jupyter/bqplot/common/tools.py
In glue we only adjust the aspect ratio of figures when the data and axes aspect ratio differ by more than 1% (see [here](https://github.com/glue-viz/glue/blob/6b968b352bc5ad68b95ad5e3bb25550782a69ee8/glue/viewers/matplotlib/state.py#L198)) - so we should also use this tolerance when deciding whether to return a CircularROI for a selection. I also think 1% is perhaps a little high so I have [another PR](https://github.com/glue-viz/glue/pull/2189) to lower the tolerance in glue-core.
This should fix https://github.com/spacetelescope/jdaviz/issues/569
> Set tolerance for determining whether to use a circular or elliptical ROI

- CHANGES.rst
- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/histogram/viewer.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/profile/viewer.py
- glue_jupyter/bqplot/scatter/viewer.py
This works as for the Matplotlib viewers and I think users should be familiar with the icon.
> Added 'home' tool in bqplot viewers to reset limits

- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/common/toolbar_vuetify.py
This does two things:
* It keeps better track of what callbacks we enable/disable when activating/deactivating tools
* It fixes the tools in the case where a single-shot (non-checkable) tool is used
> Improvements to tools

- glue_jupyter/common/state_widgets/layer_profile.py
- glue_jupyter/common/state_widgets/layer_profile.vue
The `vmin`, `vmax` and `percentile` options are currently included in the profile viewer `Layer` options, but they aren't editable by the user and don't really do anything in the profile viewer. They seem to be related to color scaling in the 2D viewers and thus aren't relevant to the profile viewer, so I removed them.
> Remove layer options that aren't relevant to profile viewers

- CHANGES.rst
- glue_jupyter/bqplot/image/frb_mark.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
- setup.cfg
This resolves a long standing issue that when in equal aspect ratio mode the figure used to always be square which did not make an efficient use of the available screen space, and caused issues in tabbed viewer mode, e.g. Jupyter Lab or jdaviz. With the latest change:
However this isn't ready yet - for now I need to manually call _setup_view_listener after the bqplot image is visible, otherwise the ViewListener does not find the view.
@maartenbreddels - this might be a good starting point for experimenting with possible fixes for ViewListener
> Improve display of equal aspect ratio mode in image viewer

- CHANGES.rst
- glue_jupyter/bqplot/image/viewer.py
Before this change, this is what happened:
> Attach ViewListener to different bqplot plot element to not include selectors

- CHANGES.rst
- glue_jupyter/bqplot/image/frb_mark.py
- glue_jupyter/bqplot/image/viewer.py
Region selections were broken in the image viewer in v0.6
> Fix broken selections in image viewer

- CHANGES.rst
- glue_jupyter/bqplot/image/frb_mark.py
- glue_jupyter/bqplot/image/layer_artist.py
This does some small optimizations with FRBMark updating to avoid updating too many times when adding a layer
> Avoid duplicate draws in FRBMark

- glue_jupyter/widgets/layer_options.py
Alternative to #250 - we weren't connecting the callback in the right place, and were ending up in a state where the layers state had been updated but not layer artists. This uses private API but in glue-core so this is fine (though we should probably expose this publicly anyway).
> Fix updating of layers list

- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/ipyvolume/common/viewer.py
See this upstream change from 2018:
* glue-viz/glue#1793
p.s. Ugh, I was trying out [GitHub's new repo editor](https://twitter.com/github/status/1425505817827151872) and it made me push changes to my fork's `master` branch, so here we are...
> MNT: glue-core uses override_mode since 2018

- CHANGES.rst
- glue_jupyter/bqplot/image/layer_artist.py
- glue_jupyter/table/viewer.py
Better handle case where image_artist has already been removed, and gracefully handle incompatible subsets in table viewer.
> Improve subset handling

- CHANGES.rst
- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/image/frb_mark.py
- glue_jupyter/bqplot/image/state.py
- glue_jupyter/bqplot/image/viewer.py
I **think** this will resolve https://github.com/spacetelescope/jdaviz/issues/564
> Expand fixed resolution buffer beyond the image boundaries to make panning seamless

- CHANGES.rst
- glue_jupyter/table/viewer.py
To use this, one needs to pass component IDs to the ``hidden_components`` property on the table viewer state - for example in Mosviz:
```python
data = mosviz.app.data_collection[0]
viewer = mosviz.app.get_viewer_by_id('mosviz-3')
viewer.state.hidden_components = [data.id['Images'], data.id['1D Spectra']]
```
> Provide a way to hide columns in the table viewer

- CHANGES.rst
- azure-pipelines.yml
- glue_jupyter/bqplot/histogram/layer_artist.py
- glue_jupyter/bqplot/image/layer_artist.py
- glue_jupyter/bqplot/profile/layer_artist.py
- glue_jupyter/bqplot/profile/viewer.py
- setup.cfg
I need to figure out if this code is still needed, but for now it seems it definitely isn't for specviz, so this branch can be used with specviz to avoid rescaling all the time.
> Disable resetting of y_min/y_max in layer artist

- glue_jupyter/table/table.vue
Long text in the table is pushing text of other cells out of view:
With this PR the content is truncated and on hover a tooltip appears with the full text:
> feat: truncate text that doesn't fit and show tooltip with full text

- glue_jupyter/ipyvolume/common/tools.py
- setup.cfg
Addressing #237, this replaces the `-Wignore` pytest option from #238 with more specific `filterwarnings` for the `DeprecationWarning` instances and setting `error` for any that would be missed. All but one actually originate from various upstream modules. So unless I am missing some error in usage of those modules all to be followed up on would be reporting the warnings upstream.
And take care of the two in `glue` itself, of course – `astype(np.float)` is straightforward; replacing `imp` could be a bit trickier.
Getting rid of `np.matrix` in the second commit was also trivial since `Projected3dROI` has already cast `projection_matrix` to `asarray` all along.
> Catch DeprecationWarnings by specific filterwarnings / fixes

- glue_jupyter/widgets/subset_select_vuetify.py
This fixes the bug where when the last subset is deleted, the dropdown menu and display behaviors do not make sense.
* Fix spacetelescope/jdaviz#642 cc @camipacifici
* Fix spacetelescope/jdaviz#216 cc @PatrickOgle
> BUG: Deselect when all subsets deleted

- glue_jupyter/bqplot/scatter/layer_artist.py
```
bqplot/marks.py:709: DeprecationWarning: default_opacities is deprecated, use opacities instead.
```
https://github.com/bqplot/bqplot/blob/d8fae93274422e72b7ecf1f464d8d8197103a28d/bqplot/marks.py#L703-L711
@maartenbreddels and @astrofrog should double check that this patch is correct.
> default_opacities is deprecated, use opacities instead

- CHANGES.rst
- glue_jupyter/bqplot/histogram/layer_artist.py
- glue_jupyter/common/state_widgets/layer_histogram.py
This PR connects the opacity of the bars in the histogram viewer to the `alpha` value of the corresponding glue layer state, and adds a corresponding `FloatSlider` in the histogram layer state widget to allow control of this parameter through the UI.
> Link opacity of histogram bars and layer state

- azure-pipelines.yml
to skip `PublishTestResults` task and get rid of warnings about missing ResultsFiles - https://github.com/glue-viz/glue-jupyter/issues/237#issuecomment-1036395402.
Also skip `coverage` tasks, which errored (though without consequences).
> Mark `notebook` and `docs` non-publishable

- glue_jupyter/widgets/subset_select_vuetify.py
This PR is to:
* Fix spacetelescope/jdaviz#928
Workflow:
1. Download notebook from https://github.com/spacetelescope/jdat_notebooks/tree/main/notebooks/IFU_cube_continuum_fit
2. Only run the code in it to download data and load it into Cubeviz; ignore everything else.
3. In the top-left image viewer, create 9 subsets. All circles are fine. Overlap or not doesn't matter.
4. Delete Subset 2.
5. Delete Subset 7.
6. Delete Subset 9. Without this patch, you will see `IndexError`.
7. Bonus: Delete the rest of the subsets, bottom up. Without this patch, another error will appear when you delete the last one. I cannot tell if this patch renders #266 unnecessary or not. @eteq , you should double check.
Somewhat related: #266 , #293
Disclaimer: I don't grok the VueJS and Glue internals, so more …
> BUG: sync_selected_from_ui to handle IndexError

- CHANGES.rst
- glue_jupyter/bqplot/image/frb_mark.py
Sometimes, `self.shape` can have zeroes and causes out of bounds error.
Fix spacetelescope/jdaviz#1102
Pairs well with #270 for the other common error when dealing with subset deletions, and maybe red wine.
> BUG: Fix out of bounds when viewer shape is zero

- CHANGES.rst
- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/common/state_widgets/layer_scatter.py
This PR enables setting `fill` attribute in scatter plot and also exposes the option as a checkbox in GUI.
> FEAT: Expose fill attribute for scatter plot

- notebooks/Astronomy/GAIA/Distance to The Pleiades with Glupyter and Gaia DR2.ipynb
Notebook from #28 no longer runs with positional argument calls. This updates the call signature to use keywords. Notebook does not crash anymore with this patch. Fixing science content is out of scope.
cc @eteq
> BUG: Fix Gaia example notebook

- CHANGES.rst
- glue_jupyter/bqplot/common/viewer.py
In order to accommodate multiple event callbacks, the mouse interact on the bqplot viewers currently listens for the set of events that is the union of all events specified via calls to `add_event_callback`. Currently, however, when any one of these events is detected, all callbacks are fired, regardless of whether or not it is one of their specified events.
To fix this issue, this PR modifies the viewer's mouse interact listener to check whether the current event is one of the callback's specified events before firing it.
> Only trigger event callbacks on their specified events

- glue_jupyter/bqplot/common/viewer.py
I think this should fix the issue mentioned at the end of #279. The key logic for the events dictionary seems to be working fine...I just forgot to connect it to where the callback gets removed, so trying to remove a method callback gives a `KeyError`.
@pllim I ran this through the jdaviz test suite locally, and everything passed (after getting the same error as the CI did before making this fix). If it would be possible for you to run it through the jdaviz CI that would be great. Sorry for any inconvenience this problem caused!
> Fix issue with removing event callbacks

- azure-pipelines.yml
- setup.cfg
Currently the majority of tests on 3.10 are failing with
```python
FAILED glue_jupyter/tests/main_test.py::test_state_widget_notebook - DeprecationWarning: There is no current event loop
ERROR glue_jupyter/tests/main_test.py::test_default_components - AttributeError: module 'collections' has no attribute 'Mapping'
ERROR glue_jupyter/tests/main_test.py::test_viewer_state - AttributeError: module 'collections' has no attribute 'Mapping'
ERROR glue_jupyter/tests/main_test.py::test_layer_state - AttributeError: module 'collections' has no attribute 'Mapping'
ERROR glue_jupyter/tests/main_test.py::test_add_data_with_state - AttributeError: module 'collections' has no attribute 'Mapping'
ERROR glue_jupyter/tests/main_test.py::test_data_names[histogram1d] - AttributeError: module 'collections' …
```
> Require ipyvolume 0.6.0 on Python 3.10

- glue_jupyter/widgets/glue_float_field.vue
A roundtrip can cause 1e2 to directly reformat to 100,
instead, we now try to keep the original formatting in the frontend.
Fixes https://github.com/spacetelescope/jdaviz/issues/1188
cc @PatrickOgle
> fix: do not reformat float numbers in text fields

- glue_jupyter/bqplot/compatibility.py
- glue_jupyter/bqplot/scatter/layer_artist.py
A future version of bqplot (0.13.0) will split off the webgl part
into a bqplot-gl package.
This will make it work with that future version, I'm just not sure how we need to optionally depend on bqplot-gl
> feat: make compatible with future versions of bqplot

- glue_jupyter/bqplot/profile/layer_artist.py
- setup.cfg
It might be useful to switch off GL, using the `USE_GL` variable. Requires https://github.com/glue-viz/bqplot-image-gl/pull/58
> Use LinesGL for faster rendering of lines.

- CHANGES.rst
- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
@kconroy - this will help towards the issue you were seeing, however there is still an issue remaining on the bqplot side as demonstrated in this notebook: https://gist.github.com/astrofrog/9069845bef13e20afe5a536550cb6811 - I'll investigate further
> Change all bqplot limits in one go when glue viewer state limits are updated

- docs/developer_notes.rst
- glue_jupyter/app.py
- glue_jupyter/bqplot/scatter/viewer.py
- glue_jupyter/registries.py
- glue_jupyter/table/viewer.py
- glue_jupyter/tests/data_viewer_test.py
- glue_jupyter/tests/test_viewer_registry.py
- setup.cfg
This PR adds a registry of viewer types (analogous to `qt_client` in QTglue). It allows an external plug-in to define a new viewer that is then available to the glue_jupyter application `new_data_viewer` function. The new viewer class is registered via a decorator which allows the developer to specify a nice string name for ease of creating a new viewer.
`app = gj.jglue()`
`s = app.new_data_viewer('externalviewer')`
This PR addresses #134 and mostly uses the jdaviz code referenced therein for the `ViewerRegistry` logic.
> Add registry for adding viewers from plugins

- glue_jupyter/bqplot/image/viewer.py
When data loading is done before the viewer is displayed, the composite image is not initialized. Calling update when the viewer is displayed fixes this.
See: spacetelescope/jdaviz#1243
To reproduce, make a notebook with two cells:
Cell 1:
```python
import warnings
warnings.simplefilter('ignore')
from jdaviz import Mosviz
import tempfile
from zipfile import ZipFile
from astropy.utils.data import download_file
import pathlib
mosviz = Mosviz()
data_dir = tempfile.gettempdir()
example_data = 'https://stsci.box.com/shared/static/ovyxi5eund92yoadvv01mynwt8t5n7jv.zip'
fn = download_file(example_data, cache=True)
with ZipFile(fn, 'r') as sample_data_zip:
sample_data_zip.extractall(data_dir)
data_dir = (pathlib.Path(data_dir) / 'mosviz_nirspec_data_0.3' / 'level3') …
```
> fix: composite image not initialized when viewer is not displayed

- CHANGES.rst
- glue_jupyter/bqplot/image/tests/test_viewer.py
- glue_jupyter/bqplot/image/viewer.py
Ideally it would be good to understand why echo is calling the callbacks when the value doesn't change, but this fix will do for now.
> Fixed a bug that caused the image viewer zoom to be reset when adding additional datasets

- CHANGES.rst
- glue_jupyter/bqplot/profile/layer_artist.py
- glue_jupyter/common/state_widgets/layer_profile.py
- glue_jupyter/common/state_widgets/layer_profile.vue
- setup.cfg
This accompanies https://github.com/glue-viz/glue/pull/2292 to expose the `as_steps` switch in the layer options widget, and handling toggling `as_steps` in the bqplot layer artist for the profile viewer.  The actual binning logic is adopted from https://github.com/astropy/specutils/blob/main/specutils/spectra/spectral_axis.py#L42.
> as_steps support in profile viewer

- glue_jupyter/widgets/layer_options.py
- glue_jupyter/widgets/layeroptions.vue
Supersedes #313 and #284
* Closes #313
* Closes #312 
We now make use of a trait, which automatically gives us a debounce, after the fix in [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/issues/3469).
Also, we use the same trait for input and output (using v-model) instead of using a different trait (as in #313) or custom methods. Using a different trait for setting can cause loops or setting to old values when there is high latency.
> fix: prevent color picker from entering an update loop

- glue_jupyter/bqplot/image/frb_mark.py
This is a direct follow-up of #318 . Without this patch dev job is failing at Jdaviz.
> BUG: Only recast float if image is not None

- .github/release.yml
- CHANGES.md
Follow-up to #321 with auto-generated PR URLs and rule to skip `no-changelog-entry-needed` PRs.
> Add rules for labels to be skipped in changelog

- glue_jupyter/bqplot/scatter/layer_artist.py
Fixes https://github.com/spacetelescope/jdaviz/issues/1664
> fix: if image is not used in scatter layer, use an empty image.

- glue_jupyter/state_traitlets_helpers.py
- glue_jupyter/tests/test_state_traitlets_helpers.py
The jdaviz developers have reported an issue with the JSON to Glue State translation which causes exceptions such as here:
https://github.com/spacetelescope/jdaviz/issues/438
The cause of this is that if the glue state has a ``CallbackList`` on a State with e.g. n elements and the front-end sends JSON which has only m elements (where m<n), this triggers an index error. The current fix in this PR is that if the JSON list has fewer items than the ``CallbackList``, we only update the first m elements in the CallbackList.
It's easier to explore this in a notebook so I have made one here:
https://gist.github.com/astrofrog/5fcc633bafb7fda7eee1d1eda192fd33
The bottom line is that there are two (I think mutually exclusive) options when the JSON updates a ``CallbackDict`` or ``CallbackList``:
* …
> Fix IndexError that occurred in some cases during JSON to State translation

- glue_jupyter/bqplot/image/layer_artist.py
We should use super() here to make sure we are compatible with the latest changes in https://github.com/glue-viz/glue/pull/2343 and also generally to avoid code duplication.
> Fix compatibility of image viewer with recent versions of glue-core

- glue_jupyter/conftest.py
- glue_jupyter/table/tests/test_table.py
- glue_jupyter/table/viewer.py
This PR allows an empty data object to be added to the table viewer, with the intention of adding data later.
This issue was discovered in Jdaviz/Mosviz. Currently, the table data and subsequent "adding to viewer" is done dynamically, once data is parsed, and a column is ready to be added. Hence, up to this point, all initializing `Data` object already contains some parsed information (and thereby a length). We are motivated to move the initialization of the table viewer to the beginning of Mosviz to be more dynamic to the order of data being added, and found the following traceback when attempting to add an empty `Data` object to the table viewer:
```
table_data = Data(label=label)
self.app.add_data(table_data, notify_done=False) …
```
> Allow empty data to be loaded to the Table Viewer

- glue_jupyter/table/table.vue
This pull request modifies the width of the first column (row number) in the table widget to have its width calculated based on the space needed for the largest index, by assuming each digit requires 20px.
Before:
After:
> Set row number column width in Table widget dynamically from no. of digits

- .github/workflows/ci_workflows.yml
- setup.cfg
Avoid test collection failures with ipywidgets 8.0.3 on its own deprecation warnings:
> ../../opt/mambaforge/envs/glue/lib/python3.11/site-packages/ipywidgets/widgets/utils.py:64: in deprecation
warnings.warn(message, DeprecationWarning, stacklevel=stacklevel+1)
E   DeprecationWarning: Widget._active_widgets is deprecated.
Could not find another way to resolve them but blanket-ignoring (although no warning appears on `from glue_jupyter.app import JupyterApplication`, and the deprecated methods seem to be only ever called in ipywidgets own `test_widget`).
> Ignore ipywidgets 8.0 self-deprecation warnings

- glue_jupyter/bqplot/histogram/layer_artist.py
- glue_jupyter/bqplot/histogram/tests/test_viewer.py
This PR aims to address the same issue that https://github.com/glue-viz/glue/pull/2300 dealt with in Qt glue, which is that if a subset group is modified to make it empty, the corresponding histogram layer artist is not redrawn. The changes here follow essentially the same logic as in the Qt update. Note that this PR only needs to update the layer artist, since the bqplot and Qt histogram viewers use the same viewer state class.
> Fix bug where empty histogram layer does not redraw

- glue_jupyter/bqplot/histogram/layer_artist.py
- glue_jupyter/bqplot/histogram/tests/test_viewer.py
- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
- glue_jupyter/common/state_widgets/layer_histogram.py
- glue_jupyter/common/state_widgets/layer_scatter.py
- glue_jupyter/widgets/layer_options.py
- glue_jupyter/widgets/layeroptions.vue
This PR adds support for modifying the z-orders of layers in the scatter and histogram viewers. In the layer artist, this is achieved by re-ordering all of the marks of viewer's figure, sorted by layer z-order. In the UI, since we don't (yet) have anywhere to do the drag-and-drop reordering that one would do in desktop glue, this PR also adds `IntText` widgets to the layer option widgets for the histogram and scatter layers for setting the z-order. Note that in principle there's nothing that prevents a similar approach for the profile and image viewers, aside from the fact that the `IntText` widget doesn't match the Vuetify styling of their layer option widgets.
The last piece of this makes some changes to the layer options widget. Currently the layer options widget stores the index of …
> Allow adjusting z-order for scatter and histogram layers

- setup.cfg
Work around two breaking changes introduced with the release of numpy 1.24.0:
1. New deprecation warning that is breaking test collection; will be fixed with scikit-image/scikit-image#6637 once 0.20 is released.
2. API change in `np.asarray(x)`, requires update to `ipyvolume>=0.6.0a` where numpy 1.24 is supported.
> Updated ipyvolume and scikit-image requirements for numpy 1.24 compatibility

- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
When plotting data in e.g. a scatter viewer, the bqplot limits were not initially changed to match the glue state limits. I'm not sure how we missed this before!
> Fix initial limits of viewers

- .github/workflows/ci_workflows.yml
- docs/conf.py
- docs/installing.rst
- glue_jupyter/app.py
- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/common/viewer.py
- glue_jupyter/bqplot/histogram/viewer.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/profile/layer_artist.py
- glue_jupyter/bqplot/profile/tests/test_viewer.py
- glue_jupyter/bqplot/profile/viewer.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
- glue_jupyter/bqplot/scatter/viewer.py
- glue_jupyter/common/state_widgets/viewer_profile.py
- glue_jupyter/common/state_widgets/viewer_profile.vue
- glue_jupyter/ipyvolume/common/tools.py
- glue_jupyter/ipyvolume/scatter/tests/test_viewer.py
- glue_jupyter/view.py
- notebooks/Generic/demo_units_custom.ipynb
- setup.cfg
- tox.ini
This is a proof of concept of unit conversion in the profile viewer. It is a companion to the following PR in glue-core:
* https://github.com/glue-viz/glue/pull/2296
(that PR is needed for the changes here to work)
For now, this adds dropdowns for the units for the x and y axis, though note that I have not yet implemented the x axis unit conversion. The combo for the y axis currently starts off empty which means 'native units', i.e. no unit conversion, and it is then possible to select a unit. This is demonstrated in the following notebook:
https://gist.github.com/astrofrog/715239c5fb7b015019fdb414ae2b609e
Obviously we should think about what the default should be, and I think we should at least indicate in the 'no conversion' case something like 'native/data units' or similar. My plan …
> Initial support for unit conversion in profile viewer

- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/bqplot/tests/test_bqplot.py
This just calls ensure_numerical on components that are passed to cmap and size. Required if we allow categoricals to set these scalings (as in https://github.com/glue-viz/glue/pull/2317), but a fine idea anyway.
> Allow cmap and size to take cateogricals

- glue_jupyter/bqplot/image/viewer.py
This was causing ``_reference_data_changed`` to be called with ``force=True`` in situations where it didn't need to be - instead we now specifically catch the case of the numerical data changing in glue-core and call a dedicated method for this, see https://github.com/glue-viz/glue/pull/2385
Once CI passes we can merge this and do a new release without waiting for glue-core - this is equivalent to simply reverting https://github.com/glue-viz/glue-jupyter/pull/339 and glue-jupyter will work fine without - for the case of a BaseCartesianData instance that has numerical data values changing, things will work correctly once the glue-core fix is merged and released.
> Don't overload _update_data in image viewer layer artist

- glue_jupyter/bqplot/profile/tests/test_viewer.py
- glue_jupyter/bqplot/profile/viewer.py
Fix bug that caused subsets to not be created correctly in the profile viewer if unit conversion caused a flip in direction (e.g. wavelength -> frequency)
Similar to https://github.com/glue-viz/glue/pull/2393
>  Fix subset creation with unit flip

- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/icons/glue_annulus.svg
We need this for Imviz annulus support. This blocks:
* https://github.com/spacetelescope/jdaviz/pull/2240
cc @dhomeier and @astrofrog
> FEAT: Annulus draw tool

- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/profile/tests/test_viewer.py
- glue_jupyter/bqplot/profile/viewer.py
@javerbukh had been battling duplicate sub-regions appearing in his work over at https://github.com/spacetelescope/jdaviz/pull/2237 .
Here is a workflow to reproduce the bug:
1. Draw a xrange region.
2. Select the Subset generated from Step 1.
3. Select XOR tool.
4. Select another region. This would turn Subset 1 into composite subset.
What I noticed with this bug is, the composition went a level deeper than it should have:
```
AND
|__ AND
|   |__ Range
|   |__ INV
|       |__ Range
|__ INV
|__ Range
```
When it should be much simpler like this:
```
AND
|__ Range
|__ INV
|__ Range
```
Since we never heard back from SMEs about this, I decided to have a look. I asked myself why are we not seeing this on spatial subsets but it appears always on spectral subset? Then I noticed that the tools …
> Fix duplicate xrange region bug when operators are used on existing regions

- glue_jupyter/vuetify_layout.py
- glue_jupyter/widgets/subset_mode_vuetify.py
- tox.ini
We cannot re-use the same widget with multiple connections/users in Solara,
Should fix https://github.com/glue-viz/glue-jupyter/pull/363
> Feat: Solara compatible

- glue_jupyter/app.py
- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/bqplot/scatter/scatter_density_mark.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
- glue_jupyter/bqplot/scatter/tests/test_visual.py
- glue_jupyter/bqplot/tests/test_bqplot.py
- glue_jupyter/common/state_widgets/layer_scatter.py
- glue_jupyter/common/state_widgets/layer_scatter.vue
- glue_jupyter/common/state_widgets/viewer_scatter.py
- glue_jupyter/common/state_widgets/viewer_scatter.vue
- glue_jupyter/conftest.py
- glue_jupyter/state_traitlets_helpers.py
- glue_jupyter/tests/data/state_widgets.ipynb
- glue_jupyter/tests/images/py311-test-visual.json
- glue_jupyter/tests/main_test.py
- glue_jupyter/utils.py
- notebooks/Experimental/bqplot_scatter_density.ipynb
This broke at some point in the last couple of years, have added a visual regression test to make sure it doesn't break again.
I need to try and get the colormap to be correct, I don't think that ever worked but now is a good time to fix it.
Fixes https://github.com/glue-viz/glue-jupyter/issues/353
> Fix density map in scatter viewer for many points

- glue_jupyter/bqplot/scatter/layer_artist.py
Removing `BqplotScatterLayerState` from `glue_jupyter.bqplot.scatter.layer_artist` broke an application in Jdaviz:
https://github.com/glue-viz/glue-jupyter/pull/363#discussion_r1262684840
This is restoring the class; @astrofrog is it OK to just revert that change, or do you have an idea for a fix that does not need `echo`?
> Restore, but deprecate BqplotScatterLayerState

- glue_jupyter/bqplot/scatter/layer_artist.py
Fixing #375, which accidentally ended up with raising a `UserWarning`
> Raise DeprecationWarning for BqplotScatterLayerState

- glue_jupyter/common/state_widgets/layer_scatter.vue
- glue_jupyter/common/state_widgets/viewer_scatter.vue
- glue_jupyter/widgets/glue_throttled_slider.vue
Improve the layout of density scatter:
- group v-if's
- normalize spacing between elements
- make layout more compact
See: #363
> Improve layout of density scatter

- glue_jupyter/__init__.py
- glue_jupyter/app.py
Companion to https://github.com/glue-viz/glue/pull/2432 - this keeps compatibility with the older versions of glue-core but uses the new import if possible.
> Fix compatibility with future glue-core changes

- glue_jupyter/bqplot/common/tools.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
Substitute for #370 that does not alter the default behaviour (of drawing an ellipse when x and y radius are > 2 % different), to avoid issues as https://github.com/glue-viz/glue-jupyter/pull/370#issuecomment-1628892239.
Instead returning a `CircularROI` is only enforced by setting a kwarg `strict_circle=True`, which is made available as default in `BqplotTrueCircleMode` and `'bqplot:truecircle'`.
@camipacifici, @pllim I checked with the tests adapted from #370, but could not test the Jdaviz examples, since I cannot reproduce the original issue with either workflow at the moment. But replacing `BqplotCircleMode` with `BqplotTrueCircleMode` in Jdaviz tools with this PR should in hopefully fix them.
@astrofrog yet to decide if this is to be exposed by a public kwarg; also not sure if we …
> Allow enforcing exactly circular ROI in draw tool 

- docs/conf.py
- docs/developer_notes.rst
Minor, but just to avoid referring to Qt
> Use :glueviz: alias instead of :glue-qt: for main glue docs

- glue_jupyter/widgets/subset_select.vue
This PR prevents the subset menu from closing when clicking on the "delete" icon for a subset, to enable deleting multiple subsets without having to repeatedly re-open the menu manually.  This retains the behavior that the menu should close when selecting a subset when multiple selections are disabled.
Calling `toggleSubset(index)` seems to be necessary in order for internal bookkeeping to remove the entry from the menu (which used to be called via event propagation, but is not prevented with the `@click.stop`).
> Keep subset menu open when deleting a subset

- glue_jupyter/bqplot/common/tools.py
In Jdaviz, you can rotate ellipse and rectangle ROIs using Subset Tools plugin. After that is done, and user wants to click and drag the shape, without this patch, the rotation resets. This patch preserves any existing rotation. Since I really don't want to implement theta support in JS (e.g., https://github.com/glue-viz/bqplot-image-gl/blob/main/js/lib/BrushEllipseSelector.js), during the dragging phase, the gray shape has no rotation, but the rotation comes back when you finalize the drag.
cc @astrofrog and @dhomeier 
[🐱](https://jira.stsci.edu/browse/JDAT-3717)
> Preserve rotation angle under dragging for ellipse and rectangle selection tools

- glue_jupyter/common/state_widgets/layer_scatter.vue
- glue_jupyter/state_traitlets_helpers.py
Currently there are two issues with adjusting values for scatter layer options, both of which this PR fixes:
* In linear (colormap) mode, the min and max values for the cmap can't be set from the widget. If the values are updated externally, the widget will update, but changing values from the widget has no effect (that is, the value in the state is not updated). The reason for this is that the deserialization line [here](https://github.com/glue-viz/glue-jupyter/blob/main/glue_jupyter/state_traitlets_helpers.py#L75) catches `cmap_vmin` and `cmap_vmax` as well as `cmap`.
* The text fields used for the min/max size values in linear size mode (and those for the colormap after the above issue is fixed) update the state values to be strings rather than numbers. I think the correct fix for this …
> Fix issues with adjusting min/max values for size and cmap

- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/tests/images/py311-test-visual.json
This PR aims to resolve #392 by making the linear size scaling behave more similarly to that of the matplotlib viewer. To do this, I ended up not using the size scales for the layer, but rather following the matplotlib viewer's example and capping the size.
FWIW, my initial thought was to do something like
```
s = ensure_numerical(self.layer[self.state.size_att].ravel())
s = (s - self.state.size_vmin) / (self.state.size_vmax - self.state.size_vmin)
np.clip(s, self.state.size_vmin, self.state.size_vmax, out=s)
s *= 0.95
s += 0.05 * (self.state.size_vmax - self.state.size_vmin)
s *= self.scatter_mark.default_size
self.scatter_mark.size = s ** 2
self.scale_size_scatter.min = float_or_none(self.state.size_vmin ** 2)
self.scale_size_scatter.max = float_or_none(self.state.size_vmax ** 2)
``` …
> Make bqplot linear scatter sizes more closely match matplotlib viewer

- glue_jupyter/widgets/layer_options.py
The layer options widget currently has an issue with grayscale color strings, which are often used as the default data color (coming e.g. from [here](https://github.com/glue-viz/glue-qt/blob/main/glue_qt/app/preferences.py#L131)). This can lead to the widget for the layer incorrectly showing the layer as white, or incorrectly showing the color as that of another layer after changing the selected layer or adjusting the z-order.
This happens because grayscale colors are not valid CSS color values, and thus the Vue template can't handle them. This PR fixes this issue by converting the grayscale string to a hex value. This is the same approach used elsewhere (e.g. [here](https://github.com/glue-viz/glue-jupyter/blob/main/glue_jupyter/bqplot/scatter/layer_artist.py#L253)).
> Ensure that layer widget color is a hex value

- glue_jupyter/bqplot/compatibility.py
- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
- glue_jupyter/common/state_widgets/layer_scatter.py
- glue_jupyter/common/state_widgets/layer_scatter.vue
This adds support for showing lines in the scatter viewer.
This currently doesn't support showing variable colors along the line but I'm not sure if this is possible yet (https://github.com/bqplot/bqplot-gl/issues/18)
cc @kecnry
> Added implementation of lines in scatter viewer

- glue_jupyter/common/state_widgets/layer_profile.vue
This PR implements another request from last week's meeting, which is to expose the opacity for profile layers to the UI.
> Expose opacity in profile viewer

- glue_jupyter/common/state3d.py
- glue_jupyter/ipyvolume/common/viewer.py
- glue_jupyter/ipyvolume/common/viewer_options_widget.py
Something that was requested during the last glue meeting was to expose an option to use the native aspect ratio in the ipyvolume viewers. This PR does that.
The only subtlety here is that we have to calculate the aspect in terms of x, z, y coordinates to account for the order in which we're using the ipyvolume axes in glue.
> Allow native aspect ratio in ipyvolume viewers

- glue_jupyter/bqplot/histogram/viewer.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/scatter/viewer.py
- glue_jupyter/ipyvolume/scatter/viewer.py
- glue_jupyter/ipyvolume/volume/viewer.py
- glue_jupyter/table/viewer.py
This will stop the following warnings:
```
/Users/tom/Dropbox/Code/Glue/glue/glue/viewers/common/viewer.py:188: UserWarning: Add large data set?
warnings.warn(message)
```
which appeared too late anyway and were not a real prompt. In future we could always choose to add a UI prompt in Jupyter and re-enable this.
> Don't set large data limits since the warning appears too late anyway

- glue_jupyter/bqplot/histogram/tests/test_viewer.py
- setup.cfg
This is a test for this bug: https://github.com/glue-viz/glue/pull/2451 - as manifested in glue-jupyter (so no fix required here aside from updating the minimum required version of glue-core)
> Add regression test for bug that caused histogram viewer to crash when removing datasets

- glue_jupyter/bqplot/histogram/viewer.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/bqplot/profile/viewer.py
- glue_jupyter/ipyvolume/volume/viewer.py
This PR adds missing viewers (histogram, profile, volume, _and image_) to the viewer registry.
> add histogram, scatter, and volume viewers to registry

- setup.cfg
runipy is deprecated and broken on Python 3.12; as I don't see it directly called anywhere, just trying to remove it right away.
Fixes #413
> Remove runipy from test requirements

- glue_jupyter/bqplot/image/layer_artist.py
Fix the case where ``visible`` is ``True`` but ``bitmap_visible`` is ``False`` in image viewer
> Fix support for bitmap_visible in image viewer

- glue_jupyter/bqplot/image/layer_artist.py
- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/tests/images/py311-test-visual.json
- setup.cfg
Companion to https://github.com/glue-viz/glue/pull/2453
> Make use of latest improvements to custom stretches in glue-core

- glue_jupyter/widgets/glue_float_field.vue
Currently `glue-float-field` doesn't pass `step` along to `text-field`, this PR fixes that.
> Support setting step value in glue-float-field

- glue_jupyter/state_traitlets_helpers.py
- glue_jupyter/utils.py
Fix https://github.com/glue-viz/glue-jupyter/issues/421 , maybe.
> Use ``mpl.colormaps.get_cmap`` for compatibility with matplotlib 3.9

- glue_jupyter/bqplot/common/tools.py
Pushing this as a test to avoid possible race conditions in observing both `selected_x` and `selected_y` in the BrushSelector interaction that have been speculated to cause unwanted size changes of the selection in #418.
Since the reported bug is non-deterministic and I have not been able to reproduce it at all, I have no idea if this change will help, just keeping it here for further investigation.
> Set Bqplot*Modes to observe only one `selected` state in BrushSelector

- glue_jupyter/bqplot/image/layer_artist.py
- glue_jupyter/bqplot/image/state.py
- glue_jupyter/bqplot/image/tests/test_viewer.py
- glue_jupyter/bqplot/image/tests/test_visual.py
- glue_jupyter/tests/images/py311-test-visual.json
- setup.cfg
Allow the units used to show the contour levels to be customized.
Work in progress!
> Implement unit conversion for contour levels

- glue_jupyter/view.py
This is needed for glue-vispy-viewers which has a custom toolbar subclass
> Allow viewers to use BasicJupyterToolbar subclasses

- glue_jupyter/app.py
- glue_jupyter/conftest.py
- setup.cfg
This exposes the vispy viewers as optional widgets for ``scatter3d`` and ``volshow``, as alternatives to ipyvolume.
This requires:
* https://github.com/glue-viz/glue-vispy-viewers/pull/381
> Add support for 3D VisPy viewers

- glue_jupyter/ipyvolume/common/viewer.py
This PR removes the side debug panel in the ipyvolume viewers. Thanks to @maartenbreddels for the tip on how to do this.
This also increases the default size of the figure itself from 400 -> 600px, as I couldn't see the entire bounding box with a 400px width. Happy to increase the size further if desired.
> Remove debug panel in ipyvolume viewers

- glue_jupyter/common/state3d.py
- glue_jupyter/ipyvolume/common/viewer.py
- glue_jupyter/ipyvolume/scatter/layer_artist.py
- glue_jupyter/ipyvolume/scatter/tests/test_viewer.py
- glue_jupyter/ipyvolume/tests/test_ipyvolume.py
- glue_jupyter/ipyvolume/volume/layer_artist.py
While Azmé and I were investigating the aspect ratio issue mentioned in #451, we noticed that currently, the displayed volume rendering in the ipyvolume viewer seems to be wrong (in particular, it doesn't match what's displayed in the vispy volume viewer). I believe this might also be a partial cause of #450.
I think this is an issue with axes. As an example, I looked at the reduced TAN C14 cube used in the astropy FITS cube tutorial [here](https://learn.astropy.org/tutorials/FITS-cubes.html). If I open this in vispy, I get
but with the current ipyvolume viewer I get
which is what led me to believe that the data was being passed into the ipyvolume widget incorrectly. After rearranging the axes as is done in this PR (note that `np.transpose` returns a view if possible, so we shouldn't need …
> Updates for ipyvolume viewer issues

- glue_jupyter/bqplot/image/state.py
- glue_jupyter/bqplot/image/tests/test_visual.py
@rosteen - hopefully this will fix the issue you were seeing?
> Fix issue with contour labels not updating after unit change

- glue_jupyter/common/toolbar_vuetify.py
Currently the way the Jupyter toolbar is set up, we can only use SVG icons. This is usually fine, as most of our glue-core icons are available as both png or svg. However, there are some icons (the rotation icon in the vispy viewers, for example) for which we only have pngs.
This PR updates the format that gets passed to `icon_path` to depend on the path for the icon. If a valid image MIME type can't be determined, then it raises an error.
> Allow using non-SVG icons in toolbar

- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/bqplot/scatter/scatter_density_mark.py
This PR prevents glue from broadcasting a large binary image for scatter viewers when the density map is not in use.
This still needs testing to ensure that density maps still continue to function as designed.
> Disable scatter viewer density map image broadcast when not visible

- glue_jupyter/bqplot/image/frb_mark.py
- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/tests/images/py311-test-visual.json
- setup.cfg
Allow users to take advantage of PNG compression via `ImageGL` from https://github.com/glue-viz/bqplot-image-gl/pull/109. Bumping pin for `bqplot-image-gl`.
> Choose 'png' image compression in BqplotImageView by default

- glue_jupyter/bqplot/image/frb_mark.py
- glue_jupyter/bqplot/image/viewer.py
The main motivation for ``@debounced`` is to avoid many repeated updates when e.g. panning/zooming or doing other front-end changes. However, currently, there are cases where relying on debounced is not desirable, e.g.:
```
image.state.reset_limits()
time.sleep(3)
```
In this case, if this code is in a cell, the figure won't be updated until after the sleep because the callback for the debounced update is not in a separate thread. The long-term fix would be to try and make sure glue and glue-jupyter are thread-safe and use a thread in this case, but for now, a simple fix is to simply treat updates in limits similarly to e.g. updates in ``percentile``, ``cmap`` and so on, and make sure those changes result in an immediate update in the figure.
This PR also adds a check to avoid unnecessary …
> Try and improve responsiveness when debounced isn't really needed

- glue_jupyter/common/state3d.py
- glue_jupyter/common/tests/test_state3d.py
This PR resolves #471 by using the first approach mentioned in that issue - changing `limits_cache` -> `_limits_cache` so that it isn't serialized. As mentioned in #471, this matches the structure of the VisPy viewer states.
I suppose this is a breaking change as it's changing the name of the class member. I would imagine that there aren't any clients directly manipulating the limits cache, but if there are I'm happy to use the second approach mentioned in the issue instead.
> Make limits cache private for serialization

- glue_jupyter/common/state_widgets/viewer_histogram.py
- glue_jupyter/common/state_widgets/viewer_histogram.vue
Adds user interface to handle bin adjustments and fixing the axis to new bin ranges
> Add histogram bin adjustment ui

- glue_jupyter/bqplot/image/viewer.py
- glue_jupyter/tests/images/py311-test-visual.json
- setup.cfg
Instead of always using the lowest cid view to determine the aspect ratio / shape of a Bqplot image viewer, use the last focused / resized one. `focused_at` describes the time that the window of that view was last focused, while `resized_at` describes when each viewer was last resized, so this way distortion from resizing based on a view in a popout window will be fixed once the original window is brought into focus.
Needs https://github.com/glue-viz/bqplot-image-gl/pull/112 to work. Let me know if you need this to use the old behaviour as a fallback with previous versions of bqplot-image-gl.
TODO:
> fix: use last focused/resized view to determine shape of BqplotImageView

- glue_jupyter/bqplot/scatter/layer_artist.py
- glue_jupyter/bqplot/scatter/tests/test_viewer.py
- glue_jupyter/bqplot/tests/test_bqplot.py
- glue_jupyter/common/state_widgets/layer_profile.vue
- glue_jupyter/common/state_widgets/layer_scatter.py
- glue_jupyter/common/state_widgets/layer_scatter.vue
- setup.cfg
Adding functionality for vector scaling and origins in layer state menu
> Add support for vectors in the bqplot viewers, and vector options in the layer state panel

- glue_jupyter/bqplot/scatter/tests/test_visual.py
This has uncovered two issues:
* For some reason the chromium generated plot for line style shows the line_mark_gl as not being hidden, so wonder if the visibility toggle isn't working right in chromium
* The vectors aren't respecting the layer colour currently
@CyclingNinja - would you be able to look into the latter issue?
Generated plots at https://output.circle-artifacts.com/output/job/3fd22f4d-33ec-43c3-9ed2-88c79268925e/artifacts/0/results/fig_comparison.html
> Add visual tests for vectors and line style

- glue_jupyter/common/state_widgets/viewer_histogram.vue
While I was using the histogram viewer, I noticed that there are a couple typos in the histogram viewer widget - they look like stray ends of HTML comments. This PR removes them.
> Remove typos in histogram widget
